name: Build and Test

on: 
  push: 
    branches:
      - master
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Build_And_Test:
    name: Build and Test
    runs-on: ubuntu-latest
    environment:
      name: 'Master'
    defaults:
      run:
        working-directory: .

    steps:
    - name: Notify Discord
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        # content: "Running ${{ github.workflow }} pipeline, View <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}> for details"
        avatar-url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
        embed-title: "Running ${{ github.workflow }} pipeline"
        embeded-url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        embed-description: "${{ github.event.pusher.name }} \n
                            ${{ github.event.head_commit.message }}"
        embed-color: 15105570 # orange

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install dependencies
      run: |
        curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
        pnpm install

    - name: Build
      run: pnpm build

    - name: Run Unit Tests
      run: pnpm test

    - name: Notify Discord of Failure
      if: failure()
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        avatar-url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
        embeded-url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        embed-color: 15548997 #red
        embed-title: "❌ Pipeline Failed"
        embed-description: "${{ github.event.pusher.name }} \n
                            ${{ github.event.head_commit.message }}"

    - name: Notify Discord of Success
      if: success()
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        avatar-url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
        embeded-url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        embed-color: 5763719 # green
        embed-title: "✅ Pipeline Succeeded"
        embed-description: "${{ github.event.pusher.name }} \n
                            ${{ github.event.head_commit.message }}"