name: Build

on: 
  push: 
    branches:
      - master
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: 'Master'
    defaults:
      run:
        working-directory: .

    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install Yarn
      run: npm install --global yarn

    - name: Intall dependencies
      run: yarn install

    - name: Build
      run: yarn build

    - name: Run Unit Tests
      run: yarn test
