name: Build and Test

on: 
  push: 
    branches:
      - master
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Build_And_Test:
    name: Build and Test
    runs-on: ubuntu-latest
    environment:
      name: 'Master'
    defaults:
      run:
        working-directory: .

    steps:
    - name: Notify Discord
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        # content: "Running ${{ github.workflow }} pipeline, View <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}> for details"
        avatar-url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
        embed-title: "Running ${{ github.workflow }} pipeline"
        embeded-url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        embed-description: "description"
        embed-color: 1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install Yarn
      run: npm install --global yarn

    - name: Intall dependencies
      run: yarn install

    - name: Build
      run: yarn build

    - name: Run Unit Tests
      run: yarn test
