name: Deploy

on: 
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Master'
    defaults:
      run:
        working-directory: .

    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install dependencies
      run: |
        curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
        pnpm install

    - name: Build
      run: pnpm run build

    # - name: copy file via ssh password
    #   uses: appleboy/scp-action@v0.1.4
    #   with:
    #     host: ${{ secrets.PROD_SSH_HOST }}
    #     username: root
    #     password: ${{ secrets.VPS_PASSWORD }}
    #     port: ${{ secrets.PORT }}
    #     source: build/
    #     target: var/www/html/


