name: Deploy

on: 
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Master'
    defaults:
      run:
        working-directory: .

    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install dependencies
      run: |
        curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
        pnpm install

    - name: Build
      run: pnpm build

    - name: SSH into VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_SSH_HOST }}
        username: root
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          scp -r /build/* root@your_server_ip:/path/on/vps


    - name: Transfer files via SFTP
      run: |
        echo "put /build/* /var/www/html/" > sftp_commands.txt
        sftp -b sftp_commands.txt username@your_server_ip
      env:
        username: root
        your_server_ip: ${{ secrets.PROD_SSH_HOST }}


